<?php
// Automatically generated by 
$scampi_project="ProjectName"; // default
$scampi_host="localhost";
$scampi_user="db_user";
$scampi_pass="db_sass";
$scampi_db="db_name";
$scampi_created="";

global $contigtable;
$contigtable = 'contigs';
global $arcstable;
$arcstable   = 'arcs';
mysql_connect($scampi_host,$scampi_user,$scampi_pass) or die ("<h2>MySQL error</h2>
		<p>Unable to connect to host \"$scampi_host\" using for <strong>$scampi_project</strong><br>
		".mysql_error()."
		<table>
		<tr><td>username</td><td>$scampi_user</td></tr>
		<tr><td>database</td><td>$scampi_db</td></tr>
		<tr><td>password</td><td><a title=\"$scampi_pass\">********</a></td></tr>
		</table>");
@mysql_select_db($scampi_db) or die("
		<h2>MySQL error</h2>
		<p>Unable to select database \"$scampi_db\", consider updating configuration file
		<pre>/inc/db_con.php</pre></p>");
?>
