# Site settings
title: ScaMPI
description: "Scaffolding using SOLiD Mate Pairs"
url:  "https://telatin.github.io/scampi/" # Actual base url of the website
baseurl: "/"           # url of the jekyll blog. e.g. if you set url to "mysite.com" and baseurl to "blog", the jekyll website will work on "mysite.com/blog"
author:
  name: "Andrea Telatin"
  email: "andreatelati.n@gmail.com"
  url: "https://telatin.github.io"
permalink: /:year/:month/:day/:title:output_ext

#Plugins
plugins: [jekyll-paginate, jekyll-feed, jekyll-seo-tag, jekyll-sitemap]

#Pagination
paginate: 3
paginate_path: "/page:num/"

#SEO
twitter:
  username: telatin
  card: summary
logo: /assets/img/logo.jpg
social:
  links: #List your social links here
    - https://twitter.com/telatin
    - https://www.github.com/telatin
    - https://www.linkedin.com/in/andrea-telatin/
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
lang: en_US

#Highlighter
kramdown:
  input:          GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

#Sass
sass:
  style: compressed
  sourcemap: never