<?php

$root=$_SERVER["SERVER_NAME"].$_SERVER["REQUEST_URI"];

?>
<style>
<!--

tr {
	
}
td {
	border-left:18px solid transparent;
	vertical-align:top;
	border-radius: 13px;
	-webkit-border-radius: 13px;
	-moz-border-radius: 13px;
}
td:hover {
	background: #e6f4fc;    

}
sup {
	font-size: 0.5em;
	background: lightyellow;
	padding-left: 3px;
	padding-right: 3px;
	border-radius: 3px;
	-webkit-border-radius: 3px;
	-moz-border-radius: 3px;
	
}
-->
</style>
<div style="text-align: center;">
<table style="text-align: left;vertical-align:top; width: 80%; margin: 0 auto 0 auto;">
<tr>

<td>
<h1>Rename scaffolds 
	<sup style="color:gray;" title="By default scaffolds are named after contig seeds (eg: contig0124). This tool batch renames scaffolds.">?</sup>
</h1>
<em>Substitute a keyword in scaffold names<br>(eg: "contig" with "scf")</em><br><br>
<form method="post" action="http://<?php echo $root; ?>">
	<table><input type="hidden" name="action" value="renamescaffolds" />
		<tr>
			<td>Replace:</td>
			<td><input name="replace" />
		</tr>
		<tr>
			<td>With:</td>
			<td><input name="with" />
		</tr>		
		<tr>
			<td></td>
			<td><input type="submit" value="Rename Scaffolds" />
		</tr>
	</table>
</form>


</td><td>

<h1>Join scaffolds
	<sup style="color:gray;" title="When evidences let us merge two scaffolds we can simply insert their names and mutual orientation with the common U/C nomenclature.  ">?</sup>
	
</h1>
<em>Merge two scaffolds<br>
(eg: scaffold01 <a title="Uncomplemented &rarr;" href="#">U</a> with scaffold33 <a href="#" title="Complemented &larr;">C</a>)</em><br><br>
<form  method="post" action="http://<?php echo $root; ?>">
	<table><input type="hidden" name="action" value="join" />
		<tr>
			<td>Scaffold1:</td>
			<td><input  title="Name of the first scaffold U/C" name="s1" />
			
			<span  title="Direction of first scaffold U/C">
			<input name="d1" size="1"/></span>
		</tr>
		<tr>
			<td>Scaffold2:</td>
			<td><input title="Name of the second scaffold U/C" name="s2" />
			<input title="Direction of second scaffold U/C" name="d2" size="1"/>
		</tr>		
		<tr>
			<td></td>
			<td><input type="submit" value="Join scaffold" />
		</tr>
	</table>
</form>



</td></tr>


<tr>
<td>

<h1 >Import scaffolds 
<sup style="color:gray;" title="Scaffolds generated by any program can be imported via the standard AGP format, as long as the contig names will match the dataset">?</sup></h1>
<em>Import an AGP file and<br>update scaffolding</em><br><br>
<form enctype="multipart/form-data" method="post" action="http://<?php echo $root; ?>">
	<table><input type="hidden" name="action" value="import" />
		<tr>
			<td>AGP file:</td>
			<td><input type="file" name="file" id="file">
		</tr>
		<tr>
			<td>Erase:</td>
			<td><input name="delete" type="checkbox" /><small>delete existing</small>
		</tr>		
		<tr>
			<td></td>
			<td><input type="submit" value="Import AGP" />
		</tr>
	</table>
</form>


</td><td>

<h1>Path Finder<sup style="color:gray;" title="Look for a path between two scaffolds">?</sup>
</h1>
<form enctype="multipart/form-data" method="post" action="http://<?php echo $root; ?>">
	<table><input type="hidden" name="action" value="path" />
		<tr>
			<td>From contig:</td>
			<td><input  name="c1" >
		</tr>
		<tr>
			<td>To contig:</td>
			<td><input name="c2" /> 
		</tr>		
		<tr>
			<td></td>
			<td><input type="submit" value="Crawl graph" />
		</tr>
	</table>
</form>
</td>
</tr>


</table>

</div>
<hr/>
<br>
<?

$act = $_REQUEST['action'];

if ($act == 'renamescaffolds') {
	$replace = $_REQUEST['replace'];
	$with    = $_REQUEST['with'];
	if (isset($replace) and isset($with) and strlen($replace)>0) {
		
		print "<h3>Updating table <em>contigs</em>...<h3>";
		$query = "UPDATE $contigtable SET scaffold=REPLACE(scaffold, '$replace','$with');";
		mysql_query($query) || print "<strong>MySQL ERROR:</strong><br>".mysql_errno();
		
	} else {
		print "<strong>ERROR:</strong>Please specify both the string to alter and its substitute.<br>";
	}
} elseif ($act == 'import') {


	if ($_REQUEST['delete']) {
		$query = 'UPDATE $contigtable SET scaffold=NULL';
		mysql_query($query);
		print "<p><strong>INFO:</strong><br>Existing information on scaffolding has been erased.</p>\n"; 
		
	}
	$r = rand(100000,100);
	$uploadfile = "/tmp/temp$r.agp";
	if (move_uploaded_file($_FILES['file']['tmp_name'], $uploadfile)) {
		$command = "pwd";
		print shell_exec("perl scampi_import_agp.pl -i $uploadfile -d inc/db_con.php ");
	} else {
		print "<p><strong>Warning:</strong> nothing to do.</p>\n";
	}
} elseif ($act == 'join') {

	$s1  = $_REQUEST['s1'];
	$d1  = $_REQUEST['d1'];
	$s2  = $_REQUEST['s2'];
	$d2  = $_REQUEST['d2'];
	
	$new=$s1.'-'.$s2;
	if ($d1 == 'U') { $order = 'ASC';} elseif ($d1 == 'C') {$order = 'DESC';} else { print "ERROR:<br>Direction has to be U (uncomplemented) or C (complemented)."; exit;}
	if ($d2 == 'U') { $order2 = 'ASC';} elseif ($d2 == 'C') {$order2 = 'DESC';} else { print "ERROR:<br>Direction of second scaffold has to be U (uncomplemented) or C (complemented)."; exit;}

	$q = "SELECT * FROM $contigtable WHERE scaffold='$s1' ORDER BY sid $order";
	$x = mysql_query($q);
	while ($r = mysql_fetch_array($x)) {
		$counter++;
		$sid = $counter * 10;
		$u = "UPDATE $contigtable SET scaffold='$new',sid=$sid WHERE name='$r[name]'";
		$ux=mysql_query($u) || die("Unable to operate on database.");
		
	}
	
	$q = "SELECT * FROM $contigtable WHERE scaffold='$s2' ORDER BY sid $order2";
	$x = mysql_query($q);
	while ($r = mysql_fetch_array($x)) {
		$counter++;
		$sid = $counter * 10;
		$u = "UPDATE $contigtable SET scaffold='$new',sid=$sid WHERE name='$r[name]'";
		$ux=mysql_query($u) || die("Unable to operate on database.");
		
	}
	
	print "Scaffold joined to form <strong><a href=\"scaffold.php?name=$new\">$new</a></strong>: $counter contigs.";

} elseif ($act == 'restore') {
	
	shell_exec("mysql -h mysql.4ngs.com -u proch -pkcvqlha -D telatin < contigs.sql");
}
?>
<table>
<tr>
<td>
</td>
<td>
<?
$a = file_get_contents("http://www.4ngs.com/scampi/last");
$a = str_replace("\n", "", $a);
print "<strong>Update check</strong><br>";
if ($a == $scampi_version) { echo "You are running the lastest release of ScaMPI ($scampi_version). Great!";} 
else
 {echo "A new version ($a) is available <a href=\"http://genomics.cribi.unipd.it/scampi/\">here</a>!" ;}	
?></td>
</tr>
</table>
